"""empty message

Revision ID: 4c1f289d60ed
Revises: 
Create Date: 2021-10-28 03:02:43.311379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1f289d60ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=True),
    sa.Column('senha', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_entrada', sa.DateTime(), nullable=True),
    sa.Column('data_medicao', sa.DateTime(), nullable=True),
    sa.Column('data_apresentacao', sa.DateTime(), nullable=True),
    sa.Column('aprovacao', sa.Boolean(), nullable=True),
    sa.Column('orcamento', sa.String(), nullable=True),
    sa.Column('pagamento', sa.String(), nullable=True),
    sa.Column('Usuario_id', sa.Integer(), nullable=True),
    sa.Column('Cliente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Cliente_id'], ['Cliente.id'], ),
    sa.ForeignKeyConstraint(['Usuario_id'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ambiente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('Projeto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Projeto_id'], ['Projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('tipo_arquivo', sa.String(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projeto_id'], ['Projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['Files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Fotos')
    op.drop_table('Files')
    op.drop_table('Ambiente')
    op.drop_table('Projeto')
    op.drop_table('Usuario')
    op.drop_table('Cliente')
    # ### end Alembic commands ###
